### ISSUE TITLE
How to compile for 32 bits?

### ISSUE THREAD

**Issue by samuelh2005** [Limine-Bootloader/limine-c-template#4]
Probably silly question, how can I compile for 32 bits? Currently my GTD/IDT/ISRs are for 32 bits so a 64 bit build doesn't work properly.
When I run QEMU (yes it's a `qemu-system-i386` the screen says:
![image](https://user-images.githubusercontent.com/41990982/221012792-2931efd2-5623-46f3-9f92-ac31eda26658.png)

Code:
* Full code can be found [here](https://github.com/ajh123-development/gtmos)
* `limine.cfg` found [here](https://github.com/ajh123-development/gtmos/blob/main/limine.cfg)
* `linker.ld` found [here](https://github.com/ajh123-development/gtmos/blob/main/kernel/arch/i386/linker.ld)

Anything else can be found in the many `Makefile`s.

**Comment by Mintsuki** [comment]
Hi. The Limine boot protocol does not support 32-bit kernels.
