### ISSUE TITLE
Any articles about how to get started using limine?

### ISSUE THREAD

**Issue by Lioncat2002** [Limine-Bootloader/limine-c-template#8]
Hello!
I have decided to use limine formy newest os project
but it seems that docs on limine are a bit lacking
are there any good articles that I can use as a reference?

**Comment by Mintsuki** [comment]
Hi, thanks for your interest in using Limine for your OS!

You can try to take a look at https://wiki.osdev.org/Limine_Bare_Bones and see if that answers your questions.

**Comment by Lioncat2002** [comment]
Ahh that's interesting I will have a look.
I also wanted to print characters to the screen
I found this video https://www.youtube.com/watch?v=-TwKbY1aLko
but it seems that `limine_terminal_request` has bee deprecated and removed in version 5.x.
So, how would one go about implementing character printing now?

**Comment by 48cf** [comment]
> So, how would one go about implementing character printing now?

https://github.com/mintsuki/flanterm/

**Comment by Lioncat2002** [comment]
thank you!
